# Optional for Pages Functions; safe to keep for compat
name = "jewside-web"
compatibility_date = "2025-09-17"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"
